### ISSUE TITLE
Custom cases testing

### ISSUE THREAD

**Issue by talha-khalid-qureshi** [malteos/legal-document-similarity#1]
Hi @malteos thank you for sharing this code.
Please tell me how we can test this repo with custom judicial cases.?

**Comment by malteos** [comment]
Thanks for your message! You would need to integrate a new experiment similar to `ocb` and `wikisource`. See https://github.com/malteos/legal-document-similarity/blob/972987e15a5a2da30a27053440373e34f1c97587/docsim/experiment.py#L49-L66 

This would require having the document texts, citations, and gold standard information.
